global:
  scrape_interval: 36s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "jmeter"
    scrape_interval: 5s
    static_configs:
      - targets: ["127.0.0.1:9270"]
